### ISSUE TITLE
PR to DefinitelyTyped

### ISSUE THREAD

**Issue by artemjackson** [andraaspar/BigNumber-d-ts#1]
Would you make PR with yours bignumber.js.d.ts to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo?

**Comment by andraaspar** [comment]
Hi @artemjackson , thanks for your interest. I cannot be bothered, but I don't mind you doing it. Go ahead if you think it will make the web a better place.
